# Generated by Django 5.2.3 on 2025-08-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='products/')),
                ('extrafort', models.BooleanField(default=False)),
                ('thc0', models.BooleanField(default=False)),
                ('nouvelle', models.BooleanField(default=False)),
                ('france', models.BooleanField(default=False)),
                ('caliweed', models.BooleanField(default=False)),
                ('bio', models.BooleanField(default=False)),
                ('sativa', models.IntegerField(choices=[(0, 'No'), (10, '10%'), (20, '20%')], default=0)),
                ('indica', models.IntegerField(choices=[(0, 'No'), (10, '10%'), (20, '20%')], default=0)),
                ('cbd', models.IntegerField(choices=[(0, 'No'), (10, '10%'), (20, '20%')], default=0)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
