# Generated by Django 5.2.3 on 2025-08-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubmission',
            name='caliweed',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='cbd',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='indica',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='sativa',
        ),
    ]
