# Generated by Django 5.2.3 on 2025-08-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_remove_productsubmission_caliweed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubmission',
            name='thc0',
        ),
    ]
