# Generated by Django 5.2.3 on 2025-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_productsubmission_thc0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubmission',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='extrafort',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='france',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='nouvelle',
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_cat_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_cat_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_cat_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_cat_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_cat_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_file_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_file_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_file_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_file_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='horizontal_file_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='vertical_pos_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='vertical_pos_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='vertical_pos_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='vertical_pos_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='vertical_pos_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
