# Generated by Django 5.2.3 on 2025-12-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_remove_productsubmission_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical_pos_1', models.CharField(blank=True, max_length=255, null=True)),
                ('vertical_pos_2', models.CharField(blank=True, max_length=255, null=True)),
                ('vertical_pos_3', models.CharField(blank=True, max_length=255, null=True)),
                ('vertical_pos_4', models.CharField(blank=True, max_length=255, null=True)),
                ('vertical_pos_5', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_cat_1', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_file_1', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_cat_2', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_file_2', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_cat_3', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_file_3', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_cat_4', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_file_4', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_cat_5', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal_file_5', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_cat_1',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_cat_2',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_cat_3',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_cat_4',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_cat_5',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_file_1',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_file_2',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_file_3',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_file_4',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='horizontal_file_5',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='vertical_pos_1',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='vertical_pos_2',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='vertical_pos_3',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='vertical_pos_4',
        ),
        migrations.RemoveField(
            model_name='productsubmission',
            name='vertical_pos_5',
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='generator.batchsubmission'),
        ),
    ]
